### ISSUE TITLE
How do I contribute this repository?

### ISSUE THREAD

**Issue by wshen001** [wyugen/shopify-theme-action#4]
I would like to submit some simple pull requests, however, I didn't see how do I compile the source javascript file to a `dist/index.js`, is there a predefined command defined in `package.json`? Or could you add the webpack settings into the repo?

**Comment by frunkad** [comment]
Sorry for the late reply.

You can edit `src/index.js`, which is later compiled with [ncc](https://github.com/vercel/ncc) to generate `dist/index.js`

**Comment by wshen001** [comment]
Thank you @frunkad!
